name: flutter_contact_appss
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.3+2

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logokontak.png
